### ISSUE TITLE
Quark replaces wooden pillar recipes

### ISSUE THREAD

**Issue by Nexusdog** [Corail31/corail-pillar#11]
It's there all the time when the crafting window is empty - bench or inventory.

It's free, and only started appearing after I updated the pillar extension for Quark

1.12
Forge 2443

**Comment by Corail31** [comment]
Not sure to understand.
Make sure you use the last version of Corail Pillar (3.1.3 for 1.12)

**Comment by Corail31** [comment]
I don't know if it's what you're reporting but some wooden pillars recipes are replaced by quark.
For now, i don't know if i'll change the recipe who was working before (because it's a 9X9 shaped recipe) or add a custom crafting tool for pillar (and get rid of the crafting table).

**Comment by Nexusdog** [comment]
[https://i.gyazo.com/9bfe6c7257fed93b7122e892c2f52c06.png](url)

Latest updates, I believe?

I suspect it will be Quark, it is one of those mods which seems to delight in interfering with others and messing up things surreptiously.

**Comment by Corail31** [comment]
fixed in Corail Pillar 3.2.0 (thanks for the report, it also fixed the air pillar)
