### ISSUE TITLE
Air Pillar always in crafting grid.

### ISSUE THREAD

**Issue by NicMoore88** [Corail31/corail-pillar#12]
The Air Pillar is always available in a blank inventory 2x2 crafting grid, as well as some other crafting interfaces from other mods.  You can freely take as many as you want.  
This appeared after updating Corail Pillar and one of the extensions (Quark/Botania, maybe?)

It may also be worth mentioning that JEI shows the Air Pillar recipe as an empty grid.

https://gyazo.com/27324b1bd4aa490ed3542fe8924abe9f

**Comment by Corail31** [comment]
Hi NicMoore88, i need more informations about reports ...
Version for minecraft(1.12.0 ? 1.12.1?), corail_pillar, quark and extension quark & autoRegLib
And may be, you could check which mod is in incompatibility...

**Comment by Corail31** [comment]
I finally found what is wrong, i'm going check more about it.

**Comment by NicMoore88** [comment]
Derp, don't know why I didnt think to include any basic info.  I see you've figured it out, but Ill provide info anyway, in case it helps in any way:
MC 1.12
Forge 2443
Corail Pillar 3.1.3
Tombstone 1.3.6
Quark/Bot Ext. 3.1.1
Quark r.1.2-104

**Comment by Corail31** [comment]
fixed in Corail Pillar 3.2.0 (thanks for the report indeed !)
