### ISSUE TITLE
[1.12+] Quark extension isn't yet released for Corail Pillar 4.0.0

### ISSUE THREAD

**Issue by 4karion** [Corail31/corail-pillar#14]
Hi, my game is crashing on startup. I'm using:

forge-14.22.1.2485 (on 1.12.1)
Quark-r1.3-110
corail_pillar-4.0.0-1.12
corail_pillar_extension_quark-3.1.1-1.12

Everything from Twitch App, here's my crashlog:
https://pastebin.com/MjKnCmHv

Thanks :)

**Comment by Corail31** [comment]
Hi 4Karion, the extension quark for the new version of Corail Pillar (4.0.0) isn't yet published, but is coming soon.
For now, you can't use previous versions of the extension because it's incompatible.

**Comment by 4karion** [comment]
Okay, thanks Corail ^^

**Comment by Corail31** [comment]
I let your report opened as information for players :)

**Comment by Corail31** [comment]
The extension is released, enjoy :+1:

**Comment by 4karion** [comment]
Oh, sorry, and thanks for the update! :D
