### ISSUE TITLE
Chisel updating there API, Corail Pillar is now using deprecated methods

### ISSUE THREAD

**Issue by MJRLegends** [Corail31/corail-pillar#15]
MC Version: 1.10.2
Forge Version: 12.18.3.2511
Corail Pillar: 3.2.0
Chisel: 2.0.0.14.33

Error from console: [Chisel/chisel]: MOD corail_pillar IS USING DEPRECATED IMC variation:add. This IMC type may be removed soon, please notify the author of this mod.

**Comment by Corail31** [comment]
Hi MJRLegends,
this is just a message to say the method may be removed (but not yet)
the good method is used in Corail Pillar 4.0 for 1.12 (and i'm not sure for now to update 1.10.2 to 4.0)

**Comment by MJRLegends** [comment]
Yeah it still works, but it gets quite spammy with the message being there :D and whats to say they dont remove it in chisel mc 1.10.2 too

**Comment by Corail31** [comment]
I'll make a short release (3.3) about this (in one or 2 days depending on how i spend my free time)
So, don't worry ;)

**Comment by MJRLegends** [comment]
Nice, Thank you
