### ISSUE TITLE
Is this still needed if I have Corail Pillars?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Corail31/corail-pillar#17]
https://minecraft.curseforge.com/projects/corail-pillar-extension-biomes-oplenty
Does this actually do anything I am a bit confused.

**Comment by Corail31** [comment]
@P3rf3ctXZer0 : if it was for 1.10.2/1.11.2, i'm going to publish the extensions for V4.
PS : it's just that pillars is more design and less code so it bored very fast to work on it ;)

**Comment by P3rf3ctXZer0** [comment]
At least you care about your user base. There are actual modders who don't care whether something works or not.
