### ISSUE TITLE
Rebuild mod against forge Download Latest 1.12.2 - 14.23.5.2772

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Corail31/corail-pillar#18]
The reason is - there are fixes directly implemented for texture performance increases. Using this gradle will let you increase texture loading sync and performance by almost 75% this means large modpacks - like mine will suffer significantly less.

**Comment by Corail31** [comment]
The build of my mod doesn't require to be in the latest forge, but players have to use the latest forge... it's a different thing...

**Comment by Corail31** [comment]
Any way, to my opinion, 2772 can't be the actual recommanded version as the latest optifine version is for 2729. (except if it works without trouble, i haven't tested)

**Comment by P3rf3ctXZer0** [comment]
Personally no longer use optifine.

**Comment by kreezxil** [comment]
You shouldn't build your mod against optifine anyways. That's like buying a car, but cause the roads are congested you install wings and jet. So when the car can't get lift and fly over the traffic whose at fault then? The car manufacturer? The road designer? or The manufacturer that sold you the wings with jet kit?

Optifine is the wings with jet kit mfr. We want problems that exist outside your mod to be Forge problems not Optifine problems.

**Comment by Corail31** [comment]
As i said, the build version of my jar doesn't require to be the lastest forge, but players need to use the latest forge, it's more related to the features that i want to use in forge.
This doesn't change that my mod will receive the same fix when using latest forge. (a simple example is the method giveItem or the enchantHelper)
