### ISSUE TITLE
[4.2.0-1.12] IllegalAccessError field_149784_t

### ISSUE THREAD

**Issue by kreezxil** [Corail31/corail-pillar#19]
Issue:  4.2.0-1.12 crashes dedicated server Forge 1.12.2 build 2772

Notes:
     on startup, now that error the other guy reported is in fact coming up for me. gonna try an older forge to see when it stops

crash report:
http://paste.ubuntu.com/p/WYNXK7CDk4/

fml server latest:
http://paste.ubuntu.com/p/Kkg7KMjW4p/

**Comment by kreezxil** [comment]
Also exists in 2771, 2770, 2769, 2768, and now 2767 which has different classes.

I now believe this is a mod conflict. I will attempt to find which mod is causing the problem.

**Comment by kreezxil** [comment]
so i rolled pillars mod back to 4.1.0 and that one works fine on 2772. I don't know how that other guy got the issue where it wasn't working unless he did it by using outdated java and operating systems.

**Comment by Corail31** [comment]
Actually, i can't produce it in my workspace (but i tested all the extensions except quark/botania).

**Comment by Corail31** [comment]
ok, i saw the reason : i forgot the AT manifest in the build file :s Sorry Kreez, i'll remove the version from the downloads ;) It's a little related to the fact that i'm moving my old projects to a different computer with IDEA instead of eclipse to clean them.
