### ISSUE TITLE
Light level from pillars (Suggestion)

### ISSUE THREAD

**Issue by wenlfs** [Corail31/corail-pillar#2]
The light level from pillars could be the same of the block used to craft him.

**Comment by Corail31** [comment]
Hm, good suggestion, that's right that pillars doesn't use the same light as their block origin :)

**Comment by wenlfs** [comment]
Oh, that was fast. It will work to Quark pillars? They give me the idea to write this suggestion, your pillars would be a more nice aspect to use crystals for decoration. I don't test it for myself.
And, they will be add for previous MC versions? I'm playing 1.10.2 yet

**Comment by Corail31** [comment]
I'll release tomorrow the others versions. (and yes it should work with quark with but i didn't test)
