### ISSUE TITLE
Using forge 1.14.2 25 and this mod cause a broken world.

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/corail-pillar#20]
![2019-06-15_17 14 34](https://user-images.githubusercontent.com/4427684/59557208-68a22f00-8f91-11e9-85d8-517979f225e6.png)
![2019-06-15_17 15 50](https://user-images.githubusercontent.com/4427684/59557209-6a6bf280-8f91-11e9-9d41-42b452cf3cff.png)

**Comment by Corail31** [comment]
It's logic, it's said on the changelog to not used it with version above 11 (as forge added forge registries for recipeSerializers just after and the frozen states ;)

**Comment by Corail31** [comment]
The new version is for latest forge ;)
