### ISSUE TITLE
 Client crash on load - java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by ProsperCraft** [Corail31/corail-pillar#21]
https://gist.github.com/ProsperCraft/502b0892893c826ab9b59c286985b496

**Comment by Corail31** [comment]
Hi Goshen, you're a friend but this doesn't change this is not the way to post issues... i have no idea what you're doing and what mods you're using...
But my mod is working with the version shown on the changelog (as the last issue that you opened without reading this changelog), and has been tested to work...
So don't open issue that doesn't target my mod.

**Comment by ProsperCraft** [comment]
Pillars was the only mod installed.

Forge updated several times today, and I missed the update.  Updating forge fixed the issue.
