### ISSUE TITLE
[1.14.4] no return of block

### ISSUE THREAD

**Issue by sarifynna** [Corail31/corail-pillar#23]
No block is returned upon breaking a placed pillar. The same issue that you fixed with your woodcutter mod maybe? Happens with vanilla blocks and blocks from your biomes o'plenty pillar extension.

corail_pillar-4.5.2-1.14.4
corail_pillar_extension_biomesoplenty-4.1.0

**Comment by Corail31** [comment]
Hi Sarifynna, Goshen asked me the same yesterday :)
NB : as it's minor, i'll only fix it in some days.

**Comment by sarifynna** [comment]
> Hi Sarifynna, Goshen asked me the same yesterday :)
> NB : as it's minor, i'll only fix it in some days but if you want a fix for your server or single play, just ask me on curseForge or on discord ;)

I can wait, thanks!

**Comment by TheDarkPreacher** [comment]
Hey, Corail, any update on this? No rush, just wondering.

**Comment by Corail31** [comment]
fixed in 4.5.3

**Comment by TheDarkPreacher** [comment]
Awesome! Thanks, Corail!
