### ISSUE TITLE
Corail items disappeared (items could not be found upon startup) - mods need to update to forge 45 if they use fml events

### ISSUE THREAD

**Issue by bloodconfetti** [Corail31/corail-pillar#24]
I have no idea what's going on... I feel like I'm going insane. I have corail_pillar-4.5.3-1.14.4 in my mod folder, and have upon the last 7 or so logins... but then I login this time and I get a message that Forge can't detect the Corail items, and asks if I want to continue and if so it will make a backup. I said yes, pulled up my inventory in Creative mode, and indeed the Corail Pillar tab is gone, but it's still in my mods folder.

Using forge: 28.0.45, minecraft 1.14.4

[latest.log](https://github.com/Corail31/corail-pillar/files/3484834/latest.log)
not sure if that will help or not...

Also, the only difference was that I had just added this mod: QuickLeafDecay-MC1.14.4-1.2.5.jar so maybe it's a weird conflict?

eta: I just loaded in again, and now it's reappeared... hm.

eta2: lmao it happened again (sorry, I'm loading in mods and wanting to check them individually to see what's working with what. This time I loaded in the mod forbidden_arcanus-1.14.4-1.0-Beta-2.jar if that means anything.) took a cap for you for what it says when I load in first thing:
![corail missing](https://user-images.githubusercontent.com/53692357/62755591-d880e300-ba31-11e9-9a90-b64f9e89a708.png)
and my current mods:
![mods so far 2](https://user-images.githubusercontent.com/53692357/62755613-f3535780-ba31-11e9-8e06-3484ea5daef8.png)
ugh and just found out other tabs are messed up. I doubt it's an issue with your mod but with Forge or with me... I don't know.

**Comment by Corail31** [comment]
Hi Bloodconfetti, and i think i can explain you what happen actually with forge 45 :)
In fact, in this version, some events from the fml package have been moved to another place, making some events breaking with previous versions.
But strangely, theses mods succeed to load any way (i saw it with biomesoplenty and some related recent issues).
So, for now, and it would be hard for you to know the mods really requiring to update (for example, pillar doesn't use theses events), perhaps it's better to wait the mods to update and stay on 44 and below... ^^

**Comment by Corail31** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/1444
seem like you reported one :)

**Comment by bloodconfetti** [comment]
Aww, okay thank you so much!! I appreciate the kind and thoughtful response ♥

**Comment by bloodconfetti** [comment]
Hmm... I just got this comment: https://github.com/itsmeow/betteranimalsplus/issues/82#issuecomment-520182097 stating they think your mod is not up to date, but I know you've been doing lots of testing and also think it's a different mod. But just letting you know in case you want to ask them why they think that, if it might help.

**Comment by Corail31** [comment]
I won't consider really what can say "meow"....
