### ISSUE TITLE
Incompatibility with Crafting Station (Tfarcenim)

### ISSUE THREAD

**Issue by Wissi** [Corail31/corail-pillar#26]
Heyo Coraill...

Hope all is well, we had a client crash recently and another mod suggest it might be your mod causing it?

Full log [here](https://gist.github.com/Wissi/08b2f734c592040fa7d579eff292c28f).

And the Thread that suggests it is [here](https://github.com/Tfarcenim/crafting-station/issues/33#issuecomment-549201782).
Second Thread point to Corail Pillars [here](https://github.com/YaLTeR/MouseTweaks/issues/28#issuecomment-549201890).

Hope all is good. Ttyl.

**Comment by Corail31** [comment]
No hurry for me to update as only its mod will crash because he doesn't use the same implementation as vanilla. But as long as i explained him why he crash and how to fix (one week ago?), there's a long time he should have patch its mod to use the same as vanilla...

**Comment by Corail31** [comment]
https://github.com/Tfarcenim/crafting-station/issues/33

**Comment by WenXin20** [comment]
Will this fix be released for 1.14.4 soon? I get this error every time I open the crafting station in red text of the player chat.

**Comment by Corail31** [comment]
Hi WenXin20,
Sure, in some days, i would like to add some changes that were in 1.12.2 before.
NB : the message is only the choice of tfarcenim ;p

**Comment by Corail31** [comment]
@WenXin20 done ;)
