### ISSUE TITLE
[feature request] rename files to have Corail in front

### ISSUE THREAD

**Issue by Zygus42** [Corail31/corail-pillar#4]
Could you please rename download files to have Corail in front so that it sorts properly in mods folder.  Would be a great help for mod pack developers.

**Comment by Corail31** [comment]
So, you're talking about extensions, that the filenames who start with pillar and not corail_pillar.
=> np, to change this

**Comment by Zygus42** [comment]
As an example, I change pillar_extension_biomesoplenty-2.2.0-1.12.0 to corail-pillar_extension_biomesoplenty-2.2.0-1.12.0.  So that the sub-mod is together with the main mod in the mods folder.

**Comment by Corail31** [comment]
It'll be done on next release of these extensions (probably just after the release of Corail Pillar about Chisel Mod)
