### ISSUE TITLE
corail pillars quark and forestry crashing on launch(1.12)

### ISSUE THREAD

**Issue by SDUBZ** [Corail31/corail-pillar#5]
Forge: 1.12-2413
corail pillars quark: pillar_extension_quark-2.2.0-1.12.0.jar
forestry: pillar_extension_forestry-1.1.0-1.12.0.jar
corail pillar: corail_pillar-2.2.0-1.12.0

crash report: 
[crash-2017-07-15_16.45.42-client.txt](https://github.com/Corail31/corail-pillar/files/1150132/crash-2017-07-15_16.45.42-client.txt)

[crash-2017-07-15_16.42.14-client.txt](https://github.com/Corail31/corail-pillar/files/1150133/crash-2017-07-15_16.42.14-client.txt)

**Comment by Corail31** [comment]
The last release of Corail Pillar (and its extensions) is for  Forge 14.21.1.2406
I have to finish the chisel release before updating to last forge.

**Comment by SDUBZ** [comment]
oh okay i will test with older forge

**Comment by Corail31** [comment]
No, it's not the problem i think :)
I tried the last forge with forestry_1.12-5.4.3.129 without trouble, i'm going to try with last quark/botania.

**Comment by Corail31** [comment]
could you give me the complete crash report on https://pastebin.com ?

**Comment by Corail31** [comment]
my mod is loaded after all mods, and it seems that you reached the maximum of blocks :)
try to remove some mods and it should works. Keep me informed :)

**Comment by SDUBZ** [comment]
what it was working in earlier versions and now its not, so how could it be block limit?

**Comment by Corail31** [comment]
It isn't from my mod, but from the game limit of block.
You have too much mod that use lots of kind of blocks.

**Comment by SDUBZ** [comment]
well actually before i updated the game over 190 mods with the earlier versions of the mod and it never ran into this limit so why now is what im trying to understand

**Comment by Corail31** [comment]
The number of block hasn't increased from my mod but perhaps others.

**Comment by SDUBZ** [comment]
i will make another instance and see if it still happens ok

**Comment by Corail31** [comment]
I try this one on your list : mbm (master blocks mod) and it used 900 blocks on its standalone version. So take care of this ;) (for an idea, Corail Pillar use only 55 when standalone)
