### ISSUE TITLE
Torch on pillar : flame is not at the good place

### ISSUE THREAD

**Issue by Corail31** [Corail31/corail-pillar#6]
When a torch is placed on a pillar, it's replaced by a custom torch (with no item version) that fit to the bounds of the pillar, but the flame is not at the good position (animation smoke/flame)
Will be fixed in next release of Corail Pillar
NB : thanks to boosterdev for the report

**Comment by Corail31** [comment]
fix in release 3.1.0 (placement of torch on block near too)

**Comment by boosterdev** [comment]
your welcome 👍
