### ISSUE TITLE
[feature request] recipe for Pillar Adjuster

### ISSUE THREAD

**Issue by Zygus42** [Corail31/corail-pillar#7]
corail_pillar-3.1.0-1.12.0

Would be nice if the Pillar Adjuster was craftable - I guess could also be an option in the config if you wanted it to be craftable or not.

**Comment by Corail31** [comment]
What would be the recipe and how should the durability of the object work? (And don't you think that the right click that turns a thin pillar into normal would be "cheated" ?)

**Comment by Zygus42** [comment]
I hadn't even looked at the recipes to realize that 2 thin = 1 thick.  Was thinking of it in purely decorative terms.  In Survival, I guess you are correct and it would be cheating.  

As an alternative, how about recipes to change a Thick back into 2 Thins ?  So then you can at least experiment with the look of your building without wasting resources.

**Comment by Corail31** [comment]
The recipe 1 normal => 2 thin is a good idea.
For the pillar_adjuster, with the new json system for recipe, it could be done by users too (the id is corail_pillar:pillar_adjuster). I'll see in next release about a recipe for it but with a survival context.

**Comment by boosterdev** [comment]
left over pillars will go perfectly into a furnace.

**Comment by Corail31** [comment]
The recipe 1 normal => 2 thin pillars has been added to release 3.1.1
