### ISSUE TITLE
forestry: hardness of the plank pillars

### ISSUE THREAD

**Issue by boosterdev** [Corail31/corail-pillar#8]
Can you adjust the strenght of the pillars like with or without axe now, we can just poke them out like a piece of grass (bare hand) atleast with the forestry pillars. regular pillars are good,
Forestry Solid Wood is good, plank version not

**Comment by Corail31** [comment]
Hi boosterdev,
I checked your report and you're right (that's why i let some states to be shown on tootip ;) )
Forestry planks pillars haven't the good hardness (to be correctly harvested), I'll fix this soon.

**Comment by Corail31** [comment]
fixed in Corail Pillar 3.1.1+
