### ISSUE TITLE
place redstone torch

### ISSUE THREAD

**Issue by boosterdev** [Corail31/corail-pillar#9]
Ok I wanted to try out the button/lever function, but uhm I kinda tried to add a redstone torch but it will not attach to the pillar sides/top,  redstone dust itself cannot be applied aswell, so i have no idea how to test it. button/lever does output to the sides of the pillar but any redstone cannot be aplied to the pillar itself, tried with forestry, quark and regular

**Comment by Corail31** [comment]
redstone torch is not allowed as redstone dust (no idea if it would be useful to add them because i don't really play to minecraft ;) )
